version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
  build:
    commands:
      - npm install --loglevel=error
      - NODE_OPTIONS=--openssl-legacy-provider REACT_APP_API_URL=http://bia-elb-dev.us-east-1.elasticbeanstalk.com/ SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - npm test